In [1]:
from load_data_json import LoadDataset 
from preprocess import VectorSpaceModel
from preprocess_restart import VectorSpaceModel2
import numpy as np
import time
from sklearn.decomposition import TruncatedSVD
from scipy.sparse.linalg import svds, eigsh
import ipyparallel as ipp
from scipy.sparse import diags


## Load the dataset
Functions to load the dataset and the given queries with associated relevant documents.

In [57]:
dataset = LoadDataset("./data/npl/npl.json", "./data/npl/queries.json", "./data/npl/qrels-treceval.txt","npl")
vsm = VectorSpaceModel(dataset.doc_matrix, dataset.name)
vsm2 = VectorSpaceModel2(dataset.doc_matrix, dataset.name)

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Sum of columns
np.sum(matrix, axis=1)


array([ 6, 15, 24])

In [80]:
start = time.time()
k=1
u, s, vt = svds(vsm.A, k=k,return_singular_vectors='vh')
print(s[-1]*s[-1])
print(vt[-1,:].T)
time.time() - start

211.25547006677417
[-0.00352576 -0.00998948 -0.00631386 ... -0.01427679 -0.00417311
 -0.00188528]


0.0530092716217041

In [ ]:
I = np.eye(6)
H = T[:7,:7].copy()
for shift in values[:5]:
    H -= shift*I
    Q, R = n

In [13]:
u, s, vt = svds(vsm.A, k=7)

In [14]:
s*s

array([ 50.13674506,  54.27794555,  55.45165415,  61.48276771,
        70.24272285, 111.38258352, 211.25547007])

In [ ]:
def tridiagonal_QR_with_shift(T, shifts):
    n = T.shape[0]
    Q = np.eye(n)
    R = T.copy()

    for shift in shifts:
        for k in range(n-1):
            # Compute Givens rotation matrix
            mu = (R[k, k] - shift) ** 2
            nu = R[k+1, k] ** 2
            r = np.sqrt(mu + nu)
            c = (R[k, k] - shift) / r
            s = R[k+1, k] / r

            # Apply Givens rotation to eliminate R[k+1, k]
            G = np.array([[c, -s],
                          [s,  c]])
            R_k_k_k_plus_1 = R[k:k+2, k:k+2]
            R_k_k_k_plus_1 = G.T @ R_k_k_k_plus_1
            R[k:k+2, k:k+2] = R_k_k_k_plus_1

            # Accumulate Q
            Q_k_k_k_plus_1 = Q[:, k:k+2]
            Q[:, k:k+2] = Q_k_k_k_plus_1 @ G

    return Q, R

1.3322676295501878e-15

In [ ]:
alpha1, beta1, q = vsm.left_lanczos((vsm.A, 20, None))

for j in range(5):
    x=alpha1.copy()
    y=beta1.copy()
    print(beta1)
    
    print(beta1)
    indices = (np.argsort(ritz))[::-1]
    q[:,:2] = q[:,:20] @ r_vectors[:, indices[:2]]
    alpha1[:2] = ritz[indices[:2]]
    
    beta1[1:3] = r_vectors[19,0:2]
    
    q[:,1] = q[:,20]
    
    for i in range(1, 20, 1):
        q_hat = vsm.A.T.dot(q[:,i])
        w = vsm.A.dot(q_hat) - alpha1[i] * q[:,i-1]
        alpha1[i] = w.dot(q[:,i])

        w = w - alpha1[i] * q[:,i]
        if i == 19:
            for k in range(i):
                w = w - beta1[k+1] * q[:,k]
        
        beta1[i+1] = np.linalg.norm(w)
        if beta1[i+1] == 0:
            break
        q[:,i+1] = w / beta1[i+1]
print(ritz)

[ 0.         50.45623942 20.22016882 33.85506989 33.01771624 20.28061975
 18.54457297 18.58114706 18.51656156 16.30654619 15.95429966 14.80736936
 14.34389578 12.05434164 13.50437876 13.39641028 15.54741726 14.59683587
 12.91042696 12.37223322 13.23556615]
[ 0.         50.45623942 20.22016882 33.85506989 33.01771624 20.28061975
 18.54457297 18.58114706 18.51656156 16.30654619 15.95429966 14.80736936
 14.34389578 12.05434164 13.50437876 13.39641028 15.54741726 14.59683587
 12.91042696 12.37223322 13.23556615]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 9 is different from 20)

In [ ]:
alpha
print(y)

[ 15.07324998 195.59731229  46.30998644  73.90444154  51.47449831
  37.32209052  32.00205979  36.44492144  40.88579563  32.7193693
  32.26858412  30.12062952  25.30269066  27.992616    26.20310685
  27.24970072  31.29729673  27.57357592  26.84492181  26.14658263]
[ 0.         51.57920914 18.15866744 31.611481   35.30124897 19.09607194
 17.8646715  15.65649793 21.03779338 18.0615023  15.88423708 15.66212483
 14.04171744 12.88713858 13.92534783 12.77042824 14.96734912 14.69369793
 13.90155657 12.87402336]


In [ ]:
ritz = 
ritz

array([200.35944854,  24.53481433,  93.68388293,  51.47449831,
        37.32209052,  32.00205979,  36.44492144,  40.88579563,
        32.7193693 ,  32.26858412,  30.12062952,  25.30269066,
        27.992616  ,  26.20310685,  27.24970072,  31.29729673,
        27.57357592,  26.84492181,  26.14658263,  12.30684446])

In [ ]:
(np.argsort(ritz))[::-1]

array([ 0,  2,  3,  7,  4,  6,  8,  9,  5, 15, 10, 12, 16, 14, 17, 13, 18,
       11,  1, 19], dtype=int64)

In [ ]:
def qr_shift(alpha, beta, mu, q):
    n = len(alpha)
    x = alpha[0] - mu
    z = beta[1]
    for i in range(n - 1):
        # Compute the Givens rotation
        if x < 1e-10:
            theta = np.pi/2
        else:
            theta = np.arctan(-z / x)
        c = np.cos(theta)
        s = np.sin(theta)
        
        beta[i] = c*beta[i] - s*z
        if i < n - 2:
            z = -s * beta[i+2]
            beta[i+2] = c*beta[i+2]

        tem_a_1 = alpha[i]
        tem_a_2 = alpha[i+1]
        alpha[i] = c*c * tem_a_1 - 2*c*s * beta[i+1] + s*s*tem_a_2
        alpha[i+1] = s*s * tem_a_1 + 2*c*s * beta[i+1] + c*c*tem_a_2
        beta[i+1] = s*c*(tem_a_1 - tem_a_2) + beta[i+1]*(c*c - s*s)
        if beta[i+1] < 1e-10:
            

        x = beta[i+1]
    return alpha, beta, q

In [ ]:
print(x)
print(y)

[192.66370187  14.14761672  45.82224272 165.81697534  95.10301781]
[ 1.11842947e-14 -2.35903450e-31  3.66538548e-15  6.36882745e+01
  8.42656671e+01  5.09152547e+01]
