In [1]:
from load_data_json import LoadDataset 
from preprocess import VectorSpaceModel
import numpy as np

## Load the dataset
Functions to load the dataset and the given queries with associated relevant documents.

In [2]:
dataset = LoadDataset("./data/med/med.json", "./data/med/queries.json", "./data/med/qrels-treceval.txt")

print(dataset.doc_matrix.shape)
print(dataset.query_vectors.shape)

(13004, 1033)
(13004, 30)


In [3]:
print(dataset.query_vectors[:,0])

  (6870, 0)	0.3861302751188736
  (6094, 0)	0.4301832750283395
  (5743, 0)	0.6021247465649711
  (3118, 0)	0.5507191208743205


# Vector Space Model ranked retrieval

Create the `vsm()` object.

In [3]:
vsm = VectorSpaceModel(dataset.doc_matrix)
print(vsm.A.shape)

(13004, 1033)


In [4]:
A_T = vsm.A.transpose()
v = np.random.rand(13004)
q = v / np.linalg.norm(v)
A_T.dot(q)

array([0.03112345, 0.05077757, 0.04616636, ..., 0.05873582, 0.06943247,
       0.07040629])

In [9]:
print(np.finfo(np.float64).eps)

2.220446049250313e-16


In [5]:
vsm.preprocess(250)

In [6]:
vsm.lanczos_vectors

[array([0.03166795, 0.01135577, 0.0517724 , ..., 0.03618807, 0.00426258,
        0.01071736]),
 array([-0.00302727,  0.03974638, -0.02794931, ...,  0.02042845,
         0.02412887,  0.05179062]),
 array([ 0.04026369,  0.02165141, -0.00137146, ..., -0.00965331,
        -0.0158526 , -0.05159497]),
 array([-0.00245947, -0.00977752,  0.01044322, ..., -0.00166099,
        -0.00315566,  0.0102339 ]),
 array([-0.0003783 ,  0.02945087, -0.00351499, ..., -0.01087657,
         0.00470596, -0.00149229]),
 array([ 0.06400428,  0.03398019,  0.01467165, ..., -0.03057972,
        -0.02601805, -0.035523  ]),
 array([-0.00241249, -0.0061196 ,  0.00511863, ...,  0.0101654 ,
         0.01110579,  0.02954168]),
 array([-0.03206338,  0.02323853, -0.02604976, ..., -0.01603839,
        -0.00676635, -0.01525108]),
 array([-0.05169846, -0.03584912,  0.01545813, ..., -0.00325135,
        -0.00736754, -0.04186948]),
 array([ 0.05902515, -0.01498524,  0.05198283, ..., -0.02524097,
         0.00319832,  0.02921874

In [7]:
count = 0
for i in range(100):
    for j in range(i):
        x = np.dot(vsm.lanczos_vectors[i],vsm.lanczos_vectors[j])
        if abs(x) > np.sqrt(np.finfo(float).eps):
            count += 1
            print(x)
print(count)

0


In [6]:
print(dataset.query_vectors[:,0])

  (6870, 0)	0.3861302751188736
  (6094, 0)	0.4301832750283395
  (5743, 0)	0.6021247465649711
  (3118, 0)	0.5507191208743205


In [63]:
q = vsm.lanczos_vectors
query = dataset.query_vectors[:,0]
query = vsm.A.T.dot(query)
print(type(q[0]))

<class 'numpy.ndarray'>


In [68]:
s = np.zeros(1033)
# query = dataset.query_vectors[:,0]

for i in range(250):
    q_dot_query = q[i] @ query
    s = s + q_dot_query * q[i]

In [7]:
vsm.response(dataset.query_vectors[:,0])

In [28]:
vsm.len

1033

In [7]:
for x in vsm.scores:
    print(x)

-0.016874686869742667
0.0039039828398941025
0.00951559179827563
0.008553783323232556
-0.00779665346797844
-0.010467998024545285
0.0005590627177374731
-0.0012838428459022693
0.007548184753502832
-0.00364272154011287
0.01679080967705228
0.014166258621232077
0.19501572011382515
0.09472735373119778
0.2200364297458988
-0.003391545347782394
0.000781320162246885
-0.0004485065336110494
-0.00010156792546984746
0.00034067225074414694
-0.006988593054482498
0.002641507242087572
-0.008997283284743092
0.005424504646065694
-0.010341456338234202
-0.01932525270937925
-0.002967569057753145
0.02854312952243184
0.007518148766607708
-0.0005219654641151629
0.006699629830386165
0.000784079884192363
0.010054473364971183
0.0023738332711288777
0.01682299933470853
-0.0011773782725248527
0.024454044375604292
0.040653359036622545
0.005986361885337155
0.005145852299283644
0.040841339655675137
0.012965587555052012
-0.0063230658778112075
0.001190440810121649
-0.004550406125016324
0.008739598484035173
0.01171264752143

In [11]:
for x in vsm.scores:
    print(x)

  (12, 0)	0.07197167520392016
  (13, 0)	0.04202672666422839
  (14, 0)	0.10220770647839855
  (40, 0)	0.010114226369323178
  (57, 0)	0.029634653837130844
  (71, 0)	0.20966040538958916
  (74, 0)	0.013545277465764474
  (78, 0)	0.06589332652447395
  (86, 0)	0.04788247596905245
  (111, 0)	0.028487067912054694
  (137, 0)	0.0517884222912767
  (141, 0)	0.047632681051577655
  (163, 0)	0.05536603004473039
  (164, 0)	0.034481237439262485
  (165, 0)	0.09335859694828254
  (166, 0)	0.07724587596283859
  (167, 0)	0.07266100128289983
  (168, 0)	0.05455683538380458
  (169, 0)	0.060256424652347894
  (170, 0)	0.09974105256342392
  (171, 0)	0.05170664327077233
  (174, 0)	0.03548509434136199
  (179, 0)	0.03255872918704592
  (180, 0)	0.09334856727291833
  (181, 0)	0.06713158051956541
  :	:
  (503, 0)	0.024587308842168983
  (504, 0)	0.011134255253378245
  (505, 0)	0.03363894088710141
  (506, 0)	0.014371655280489856
  (507, 0)	0.01226869187220455
  (508, 0)	0.030636800537320485
  (509, 0)	0.023856237748921864


In [ ]:
print("The inverted index of the collection: first 10 terms and first 10 documents per term")
for t, v in list(vsm.index.items())[:10]:
    print("Term: ", t, "\tDocs: ", list(v)[:10], "\n")

The inverted index of the collection: first 10 terms and first 10 documents per term
Term:  correl 	Docs:  [0, 385, 904, 905, 394, 911, 147, 148, 277, 153] 

Term:  matern 	Docs:  [0, 4, 5, 11, 303, 706, 324, 326, 328, 331] 

Term:  fetal 	Docs:  [0, 1, 2, 3, 4, 5, 904, 11, 277, 936] 

Term:  plasma 	Docs:  [0, 1024, 4, 5, 516, 1031, 397, 273, 147, 149] 

Term:  level 	Docs:  [0, 1, 1024, 3, 516, 517, 9, 523, 524, 525] 

Term:  glucos 	Docs:  [0, 640, 4, 518, 9, 146, 413, 297, 564, 181] 

Term:  free 	Docs:  [0, 385, 3, 4, 393, 11, 652, 275, 659, 281] 

Term:  fatti 	Docs:  [0, 386, 4, 5, 6, 7, 9, 137, 157, 158] 

Term:  acid 	Docs:  [0, 1, 4, 5, 6, 7, 520, 9, 1030, 526] 

Term:  coeffici 	Docs:  [0, 40, 305, 401, 532, 501, 502, 628, 507] 



Visualize the documents as vectors.

In [ ]:
docs_vector = vsm.docs_as_vectors()

In [ ]:
docs_vector.shape 

(1032, 9685)

Visualize the queries as vectors.

In [ ]:
example_query = queries[1]
print("Example query: ", example_query)

Example query:   the crystalline lens in vertebrates including humans


In [ ]:
query_vector = vsm.query_as_vector(example_query)

In [ ]:
query_vector.shape

(9685,)

Compute the relevance scores as the cosine similarity.

In [ ]:
scores = vsm.relevance_scores(example_query)

In [ ]:
print("The relevance scores for the given query, for each document:")
for d, s in list(scores.items())[:10]:
    print("DocID: ", d, "\tScore: ", s, "\n")

The relevance scores for the given query, for each document:
DocID:  0 	Score:  0 

DocID:  1 	Score:  0 

DocID:  2 	Score:  0 

DocID:  3 	Score:  0.021291796307282396 

DocID:  4 	Score:  0 

DocID:  5 	Score:  0 

DocID:  6 	Score:  0 

DocID:  7 	Score:  0 

DocID:  8 	Score:  0.056132485052834566 

DocID:  9 	Score:  0 



Return the top 10 documents given the query.

In [ ]:
example_query

' the crystalline lens in vertebrates including humans'

In [ ]:
k = 10
top10 = vsm.vector_space_model(example_query, k)

In [ ]:
print(f"The relevance scores for the top {k} documents:")
for d, s in list(top10.items()):
    print("DocID: ", d, "\tScore: ", s, "\n")

The relevance scores for the top 10 documents:
DocID:  71 	Score:  0.32326427430871757 

DocID:  499 	Score:  0.2662094450787526 

DocID:  180 	Score:  0.2179920012480751 

DocID:  170 	Score:  0.19139097770770058 

DocID:  14 	Score:  0.19027283535863754 

DocID:  964 	Score:  0.18674186882310087 

DocID:  165 	Score:  0.18475982417434741 

DocID:  512 	Score:  0.17601476449236989 

DocID:  137 	Score:  0.16698722946249522 

DocID:  359 	Score:  0.1503014631326245 



### Relevance Feedback

In [ ]:
example_relevant = relevance[1]
print("Relevant documents for the example query: ", example_relevant)

Relevant documents for the example query:  [12, 13, 14, 71, 78, 137, 141, 163, 164, 165, 166, 167, 168, 169, 170, 171, 179, 180, 181, 182, 183, 184, 185, 210, 211, 498, 499, 500, 501, 502, 503, 505, 506, 507, 509, 510, 512]


In [ ]:
example_non_relevant = [i for i in range(vsm.n_docs) if i not in example_relevant]
print("20 of the non relevant documents for the example query: ", example_non_relevant[:20])

20 of the non relevant documents for the example query:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 17, 18, 19, 20, 21, 22]


In [ ]:
opt_query = vsm.relevance_feedback_rocchio(example_query, example_relevant, example_non_relevant, alpha=1, beta=.75, gamma=.15)

In [ ]:
top10_rel = vsm.vector_space_model(opt_query, k)

In [ ]:
print(f"The relevance scores for the top {k} documents retrieved using relevance feedback:")
for d, s in list(top10_rel.items()):
    print("DocID: ", d, "\tScore: ", s, "\n")

The relevance scores for the top 10 documents retrieved using relevance feedback:
DocID:  498 	Score:  0.4975825553600744 

DocID:  180 	Score:  0.48248989126391234 

DocID:  510 	Score:  0.472073021470223 

DocID:  12 	Score:  0.4560654940412232 

DocID:  179 	Score:  0.45186607965425535 

DocID:  508 	Score:  0.44791318658586426 

DocID:  164 	Score:  0.42581831309501617 

DocID:  165 	Score:  0.42358178294680243 

DocID:  499 	Score:  0.4230008437357246 

DocID:  503 	Score:  0.4203885699026642 



### Pseudo-Relevance Feedback

In [ ]:
opt_query_pseudo = vsm.pseudo_relevance_feedback(example_query, k=10)

In [ ]:
top10_pseudo = vsm.vector_space_model(opt_query_pseudo, k)

In [ ]:
print(f"The relevance scores for the top {k} documents retrieved using pseudo relevance feedback:")
for d, s in list(top10_pseudo.items()):
    print("DocID: ", d, "\tScore: ", s, "\n")

The relevance scores for the top 10 documents retrieved using pseudo relevance feedback:
DocID:  14 	Score:  0.5571136148407742 

DocID:  165 	Score:  0.5392188837587554 

DocID:  512 	Score:  0.5216182443784564 

DocID:  499 	Score:  0.48581512098078977 

DocID:  180 	Score:  0.46169998787542205 

DocID:  170 	Score:  0.4382538945134972 

DocID:  71 	Score:  0.4340505106725038 

DocID:  964 	Score:  0.3458494017629007 

DocID:  137 	Score:  0.3081767502378574 

DocID:  12 	Score:  0.30238538545091015 



### Performance evaluation

In [ ]:
import numpy as np

Computing precision and recall for the given set of queries and relevant documents.

In [ ]:
map = dict()
prec = dict()
rec = dict()

min_k = 1
max_k = max([len(i) for i in relevance.values()])
prec, rec = vsm.precision_recall(queries, relevance, min_k, max_k)

In [ ]:
prec_rel, rec_rel = vsm.precision_recall(queries, relevance, min_k, max_k, rel_feedback=True)

In [ ]:
prec_pseudo, rec_pseudo = vsm.precision_recall(queries, relevance, min_k, max_k, pseudo_feedback=True)

### Average precision and recall and Mean Average Precision (MAP)

In [ ]:
def max_avg_prec(precision, queries, relevance):
    map = 0
    for qid in list(queries.keys()):
        ap = 0
        mj = len(relevance[qid])
        for k in range(1, mj+1):
            ap += precision[k][qid-1]
        map += ap / mj
    map /= len(queries.keys())
    return map

1. For the "standard" case

In [ ]:
for k in range(5, 15):
    print(f"K={k}\tAverage Precision: {np.mean(prec[k])}\t Average Recall: {np.mean(rec[k])}")

K=5	Average Precision: 0.6827586206896552	 Average Recall: 0.16281932949952388
K=6	Average Precision: 0.6551724137931034	 Average Recall: 0.19058144148202566
K=7	Average Precision: 0.6403940886699508	 Average Recall: 0.21561975105582612
K=8	Average Precision: 0.6422413793103449	 Average Recall: 0.2472395322148463
K=9	Average Precision: 0.6513409961685824	 Average Recall: 0.2792880888851007
K=10	Average Precision: 0.6413793103448275	 Average Recall: 0.3074866616191644
K=11	Average Precision: 0.6175548589341692	 Average Recall: 0.32182840087469666
K=12	Average Precision: 0.6091954022988506	 Average Recall: 0.3435653605129643
K=13	Average Precision: 0.5941644562334217	 Average Recall: 0.361982461771145
K=14	Average Precision: 0.5837438423645319	 Average Recall: 0.3843476271535518


In [ ]:
map = max_avg_prec(prec, queries, relevance)

In [ ]:
print(f"MAP: {map}")

MAP: 0.6296379359580575


2. Allowing relevance feedback - considering as relevant the known set of relevant documents

In [ ]:
for k in range(5, 15):
    print(f"K={k}\tAverage Precision: {np.mean(prec_rel[k])}\t Average Recall: {np.mean(rec_rel[k])}")

K=5	Average Precision: 0.9586206896551723	 Average Recall: 0.23514480661536444
K=6	Average Precision: 0.9540229885057472	 Average Recall: 0.28206434548418724
K=7	Average Precision: 0.9458128078817735	 Average Recall: 0.32513901843917864
K=8	Average Precision: 0.9482758620689655	 Average Recall: 0.37123503786379247
K=9	Average Precision: 0.9425287356321839	 Average Recall: 0.41206285805468973
K=10	Average Precision: 0.9344827586206896	 Average Recall: 0.45115531341052195
K=11	Average Precision: 0.9247648902821317	 Average Recall: 0.49087010231597417
K=12	Average Precision: 0.9137931034482759	 Average Recall: 0.5269035789194244
K=13	Average Precision: 0.8992042440318303	 Average Recall: 0.5588493169523775
K=14	Average Precision: 0.8866995073891624	 Average Recall: 0.5895345976903904


In [ ]:
map_rel = max_avg_prec(prec_rel, queries, relevance)

In [ ]:
print(f"MAP allowing relevance feedback: {map_rel}")

MAP allowing relevance feedback: 0.9321421215043031


3. Allowing pseudo-relevance feedback - considering as relevant the top 10 documents retrieved

In [ ]:
for k in range(5, 15):
    print(f"K={k}\tAverage Precision: {np.mean(prec_pseudo[k])}\t Average Recall: {np.mean(rec_pseudo[k])}")

K=5	Average Precision: 0.7793103448275862	 Average Recall: 0.19113517390258328
K=6	Average Precision: 0.7586206896551723	 Average Recall: 0.22187928788908468
K=7	Average Precision: 0.7389162561576356	 Average Recall: 0.24887198088278584
K=8	Average Precision: 0.7112068965517241	 Average Recall: 0.27617769102957546
K=9	Average Precision: 0.7011494252873562	 Average Recall: 0.30235656890286466
K=10	Average Precision: 0.6896551724137929	 Average Recall: 0.32787548666316174
K=11	Average Precision: 0.677115987460815	 Average Recall: 0.35559589840557104
K=12	Average Precision: 0.6781609195402301	 Average Recall: 0.3871030980689513
K=13	Average Precision: 0.6631299734748012	 Average Recall: 0.4105198274904371
K=14	Average Precision: 0.6576354679802955	 Average Recall: 0.4341823353436082


In [ ]:
map_pseudo = max_avg_prec(prec_pseudo, queries, relevance)

In [ ]:
print(f"MAP allowing pseudo-relevance feedback: {map_pseudo}")

MAP allowing pseudo-relevance feedback: 0.7072055147428038
